{
    "config": {
        "error": {
            "cannot_connect": "La conexi\u00f3n ha fallado",
            "invalid_auth": "Autenticaci\u00f3n no v\u00e1lida",
            "unknown": "Error inesperado"
        },
        "step": {
            "auth": {
                "data": {
                    "password": "Contrase\u00f1a",
                    "username": "Nombre de usuario"
                }
            },
            "user": {
                "data": {
                    "host": "Anfitri\u00f3n"
                }
            }
        }
    }
}